### ISSUE TITLE
Failure to deploy using Python project

### ISSUE THREAD

**Issue by g-farrow** [youyo/aws-cdk-github-actions#11]
I am having problems using the action for a Python-based project. It seems that the `requirements.txt` fails to install correctly, but I can't see enough debug logging to resolve it:

```
Install aws-cdk latest
Successful install aws-cdk latest
Install requirements.txt
Failed to install requirements.txt
Run cdk deploy  "*"
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from aws_cdk import core
ModuleNotFoundError: No module named 'aws_cdk'
Subprocess exited with error 1
```

Is there a known workaround, or configuration change to overcome this?
The project is built in Python 3.7
The project follows the AWS setup best practise for Python, here: https://docs.aws.amazon.com/cdk/latest/guide/work-with-cdk-python.html

**Comment by youyo** [comment]
@g-farrow 
Thanks for the issue.
Fixed a bug(#13) and added a debug_log option(#12).
Can you try again with v1.1.8?

**Comment by g-farrow** [comment]
Hi @youyo 

Thanks for the debug option. I've run it with debug on and it seems to indicate a possible permissions issue with pip, but also that git is not installed (which pip install may need?):

```
Install aws-cdk latest
/usr/bin/cdk -> /usr/lib/node_modules/aws-cdk/bin/cdk
+ aws-cdk@1.47.0
added 215 packages from 186 contributors in 8.138s
Successful install aws-cdk latest
Install requirements.txt
WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting attrs~=19.3.0
  Downloading attrs-19.3.0-py2.py3-none-any.whl (39 kB)
Obtaining authorisation_service_poc from git+https://github.com/<organisation>/<project-repo>.git@6df5db498077abedbcebac2665ad91fa6ae6fddd#egg=authorisation_service_poc (from -r requirements.txt (line 2))
  Running command git clone -q https://github.com/<organisation>/<project-repo>.git /github/workspace/src/<project-repo>
  Cloning https://github.com/<organisation>/<project-repo>.git (to revision 6df5db498077abedbcebac2665ad91fa6ae6fddd) to ./src/<project-repo>
  ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git clone -q https://github.com/<organisation>/<project-repo>.git /github/workspace/src/<project-repo>
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
Failed to install requirements.txt
Run cdk deploy  "*"
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from aws_cdk import core
ModuleNotFoundError: No module named 'aws_cdk'
Subprocess exited with error 1
```

**Comment by youyo** [comment]
Hi @g-farrow 

Are you using [actions/cache](https://github.com/actions/cache/blob/master/examples.md#python---pip)?
Sorry, I didn't test with actions/cache.
If you are using actions/cache, exclude actions/cache and could you confirm that you will be successful?

**Comment by g-farrow** [comment]
hi @youyo 

I'm not using actions cache, here is my actions config:

```
name: Master Branch
on:
  push:
    branches:
      - "master"

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_ACCOUNT: "589908197324"

jobs:
  DeployToAws:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification (START)
        #       https://github.com/marketplace/actions/slatify
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: "STARTED: '${{ github.job }}'"
          icon_emoji: lock
          mention: "here"
          mention_if: "failure"
          url: ${{ secrets.SLACK_WEBHOOK }}
      - name: Clone Repo
        uses: actions/checkout@master
      - name: CDK Deploy
        id: deploy
        uses: youyo/aws-cdk-github-actions@master
        with:
          cdk_subcommand: "deploy"
          actions_comment: false
          debug_log: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
          AWS_DEFAULT_ACCOUNT: ${{ env.AWS_DEFAULT_ACCOUNT }}
      - name: Validate Deployment Success
        run: exit 1
        if: steps.deploy.outputs.status_code == 1
      - name: Slack Notification
        #       https://github.com/marketplace/actions/slatify
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: "ENDED: '${{ github.job }}'"
          icon_emoji: lock
#          mention: "here"
#          mention_if: "failure"
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by g-farrow** [comment]
hi @youyo ,

I did some more investigation. Because my project's Lambda code requires 3rd party dependencies, it builds a package locally and sets a requirement in requirements.txt to that package - via _git_ repository link. By removing that link, the process completes successfully.

The issue is that git is not installed on the Docker image. Therefore I think the fix is to make sure git is installed.

Pull Request: #14

**Comment by youyo** [comment]
hi @g-farrow 
Thank you for your Pull Request!
v1.1.9 is now available!
Try this one!

**Comment by g-farrow** [comment]
Hi @youyo - thanks for accepting the PR. This is now fixed 👍

**Comment by greghor** [comment]
Hi @youyo and first of all, thank you for this action. 

I am actually facing the issue described above when using the last release but I still get this error

```
Install aws-cdk latest
Successful install aws-cdk latest
Run cdk deploy  "*"
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from aws_cdk import core
ModuleNotFoundError: No module named 'aws_cdk'
Subprocess exited with error 1
```

I tried with v1.1.9 but doesn't work neither.  

Any ideas what went wrong here?

Here is my workflow file:

```
name: deploy
on:
  push:
    branches: 
      - 43-gh-workflow
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checking out
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: aws-cdk-github-action
        uses: youyo/aws-cdk-github-actions@master
        with:
          cdk_subcommand: "deploy"
          actions_comment: false
          args: "-c stage=stg -c source=titi.au.bateau --require-approval never"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-west-1'
```
